#!/usr/bin/env python3
"""Read what AzerothCore already knows, so the atlas can document only what it does not.

AzerothCore implements the whole standard 3.3.5a protocol and loads the standard DBC set.
Re-documenting either would be wasted work and a second source of truth. This extracts
that baseline from the core checkout; the linter then refuses a fiche for an opcode the
core already defines, unless the fiche says explicitly that Ascension reuses the number
for something else.

  python3 tools/extract/ac_baseline.py <azerothcore checkout> --out protocol/known-baseline.yaml
"""

import argparse
import os
import re
import subprocess
import sys

OPCODE_RE = re.compile(r"^\s*((?:CMSG|SMSG|MSG)_[A-Z0-9_]+)\s*=\s*0x([0-9A-Fa-f]{1,4})\s*,")
DBC_RE = re.compile(r'"([A-Za-z_]+\.dbc)"')


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("core", help="path to the azerothcore-wotlk checkout")
    parser.add_argument("--out", required=True)
    parser.add_argument("--stock-ref", default="6f0ba8e896dec6e3c7d91e7d851e396c68bc3446",
                        help="git revision of the core whose Opcodes.h is the last one without CoA "
                             "additions (default: 'feat(Core): Add clustering support', 2026-07-27)")
    args = parser.parse_args()

    opcodes_h = os.path.join(args.core, "src/server/game/Server/Protocol/Opcodes.h")
    dbc_cpp = os.path.join(args.core, "src/server/game/DataStores/DBCStores.cpp")
    for path in (opcodes_h, dbc_cpp):
        if not os.path.isfile(path):
            sys.exit(f"not found: {path}")

    def parse(text):
        found = {}
        for line in text.splitlines():
            match = OPCODE_RE.match(line)
            if match:
                found.setdefault(int(match.group(2), 16), match.group(1))
        return found

    with open(opcodes_h, encoding="utf-8", errors="replace") as handle:
        current = parse(handle.read())
    # The CoA fork adds its own constants to Opcodes.h (SMSG_COA_*, CMSG_ANTICHEAT_*) and
    # raised NUM_MSG_TYPES, so the header alone cannot say what is stock. The last revision
    # without CoA additions can: everything it defines is the standard set; everything the
    # current header adds is the fork's name for an Ascension opcode, kept in a separate map
    # so a fiche can show the server's name next to the client's.
    shown = subprocess.run(["git", "-C", args.core, "show",
                            f"{args.stock_ref}:src/server/game/Server/Protocol/Opcodes.h"],
                           capture_output=True, text=True)
    if shown.returncode != 0:
        sys.exit(f"cannot read Opcodes.h at {args.stock_ref}: {shown.stderr.strip()}")
    opcodes = parse(shown.stdout)
    fork = {value: name for value, name in current.items() if value not in opcodes}
    limit = max(opcodes) + 1

    tables = set()
    with open(dbc_cpp, encoding="utf-8", errors="replace") as handle:
        tables.update(DBC_RE.findall(handle.read()))

    with open(args.out, "w", encoding="utf-8") as out:
        print("# Generated by tools/extract/ac_baseline.py -- do not hand-edit.", file=out)
        print("# What AzerothCore already implements. The atlas documents the complement.", file=out)
        print(f"source: {os.path.abspath(args.core)}", file=out)
        print(f"opcode_count: {len(opcodes)}", file=out)
        print(f"max_opcode: {max(opcodes):#06x}", file=out)
        print(f"stock_ref: {args.stock_ref}   # the core revision whose Opcodes.h is the standard set", file=out)
        print(f"stock_limit: {limit:#06x}   # one above the highest standard opcode", file=out)
        print("opcodes:", file=out)
        for value in sorted(opcodes):
            print(f"  {value:#06x}: {opcodes[value]}", file=out)
        print(f"fork_opcode_count: {len(fork)}", file=out)
        print("# Constants the CoA fork added above NUM_MSG_TYPES: the server's names for Ascension", file=out)
        print("# opcodes. Documented in the atlas under the client's name; shown as server_name.", file=out)
        print("fork_opcodes:", file=out)
        for value in sorted(fork):
            print(f"  {value:#06x}: {fork[value]}", file=out)
        print(f"dbc_table_count: {len(tables)}", file=out)
        print("# Tables the core's DBCStores loads. A client table missing from this list is", file=out)
        print("# 'not loaded by AzerothCore', which is NOT the same as 'added by Ascension':", file=out)
        print("# the standard client ships many tables no server ever reads.", file=out)
        print("dbc_tables:", file=out)
        for name in sorted(tables, key=str.lower):
            print(f"  - {name}", file=out)

    print(f"{len(opcodes)} opcodes, {len(tables)} DBC tables -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
