#!/usr/bin/env python3
"""Describe and compare DBC sets without copying them into the repository.

A DBC set is a *data snapshot*: a second identity axis alongside the binary build
(ADR 0004). These subcommands produce the fingerprints and deltas the atlas records, so
that a fact derived from a catalogue can say which catalogue it came from.

  manifest <dir> --id <id> --out <file>    per-table hash, record count and header
  compare  <dirA> <dirB>                   structural delta between two sets
  columns  <dirA> <dirB> <Table.dbc>       which columns differ, and whether the
                                           difference survives string resolution

`columns` resolves every differing column as if it held a string-block offset, because
that is the cheapest way to separate a repacked string block (offsets all move, the text
is unchanged) from real content change. It cannot know which columns actually are string
references: on a numeric column the resolved text is meaningless, and shows up as
`same=0` with nonsense samples. Read `as_string same=N` as evidence only when the samples
look like text.

None of these read game assets into the repository; they emit text about them.
"""

import argparse
import hashlib
import os
import struct
import sys
from collections import Counter

HEADER = struct.Struct("<4s4I")


def dbc_files(directory):
    return sorted((name for name in os.listdir(directory) if name.lower().endswith(".dbc")),
                  key=str.lower)


def resolve(directory, name):
    """Find a table case-insensitively; DBC sets disagree on capitalisation."""
    for candidate in os.listdir(directory):
        if candidate.lower() == name.lower():
            return os.path.join(directory, candidate)
    return None


class Table:
    def __init__(self, path):
        self.path = path
        with open(path, "rb") as handle:
            self.data = handle.read()
        magic, self.count, self.fields, self.size, self.string_bytes = HEADER.unpack_from(self.data)
        self.wdbc = magic == b"WDBC"
        self.string_base = HEADER.size + self.count * self.size

    def record(self, index):
        start = HEADER.size + index * self.size
        return self.data[start:start + self.size]

    def records_by_id(self):
        """Keyed on the first u32. Empty when the table cannot hold one -- CharBaseInfo
        has 2-byte records -- or when the file is truncated. Callers check uniqueness
        against `count` before trusting the result."""
        if not self.wdbc or self.size < 4:
            return {}
        if HEADER.size + self.count * self.size > len(self.data):
            return {}
        return {struct.unpack_from("<I", self.data, HEADER.size + i * self.size)[0]: i
                for i in range(self.count)}

    def string_at(self, offset):
        if offset == 0 or offset >= self.string_bytes:
            return ""
        start = self.string_base + offset
        end = self.data.find(b"\0", start)
        return self.data[start:end].decode("utf-8", "replace")

    def column(self, record, index):
        return struct.unpack_from("<I", record, index * 4)[0]

    @property
    def columns(self):
        return self.size // 4


def sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def cmd_manifest(args):
    out = open(args.out, "w", encoding="utf-8") if args.out else sys.stdout
    names = dbc_files(args.directory)
    print(f"# Generated by tools/extract/dbcinfo.py manifest -- do not hand-edit.", file=out)
    print(f"dataset: {args.id}", file=out)
    print(f"source_path: {os.path.abspath(args.directory)}", file=out)
    print(f"table_count: {len(names)}", file=out)
    print("tables:", file=out)
    for name in names:
        path = os.path.join(args.directory, name)
        table = Table(path)
        print(f"  - name: {name}", file=out)
        print(f"    sha256: {sha256(path)}", file=out)
        print(f"    bytes: {os.path.getsize(path)}", file=out)
        if table.wdbc:
            print(f"    records: {table.count}", file=out)
            print(f"    fields: {table.fields}", file=out)
            print(f"    record_size: {table.size}", file=out)
            print(f"    string_bytes: {table.string_bytes}", file=out)
        else:
            print(f"    format: not-wdbc", file=out)
    if args.out:
        out.close()
        print(f"wrote {args.out} ({len(names)} tables)")
    return 0


def cmd_compare(args):
    a_names = {n.lower(): n for n in dbc_files(args.a)}
    b_names = {n.lower(): n for n in dbc_files(args.b)}
    only_a = sorted(set(a_names) - set(b_names))
    only_b = sorted(set(b_names) - set(a_names))
    shared = sorted(set(a_names) & set(b_names))

    print(f"# tables: A={len(a_names)} B={len(b_names)} shared={len(shared)}")
    for name in only_a:
        print(f"only_in_a: {a_names[name]}")
    for name in only_b:
        print(f"only_in_b: {b_names[name]}")

    identical, differing = [], []
    for key in shared:
        pa, pb = os.path.join(args.a, a_names[key]), os.path.join(args.b, b_names[key])
        if sha256(pa) == sha256(pb):
            identical.append(a_names[key])
            continue
        ta, tb = Table(pa), Table(pb)
        entry = {"name": a_names[key], "a": ta, "b": tb}
        ia, ib = ta.records_by_id(), tb.records_by_id()
        # Only trust id deltas when the first column really is a unique key.
        if ia and ib and len(ia) == ta.count and len(ib) == tb.count:
            entry["only_a"] = sorted(set(ia) - set(ib))
            entry["only_b"] = sorted(set(ib) - set(ia))
            entry["common_differing"] = sum(1 for k in ia if k in ib
                                            and ta.record(ia[k]) != tb.record(ib[k]))
        differing.append(entry)

    print(f"identical_tables: {len(identical)}")
    print(f"differing_tables: {len(differing)}")
    for entry in differing:
        ta, tb = entry["a"], entry["b"]
        line = (f"  {entry['name']}: records {ta.count}->{tb.count}"
                f" fields {ta.fields}/{tb.fields} record_size {ta.size}/{tb.size}")
        if "only_a" in entry:
            line += (f" | ids only_a={len(entry['only_a'])} only_b={len(entry['only_b'])}"
                     f" common_differing={entry['common_differing']}")
            if entry["only_a"]:
                line += f" | a_sample={entry['only_a'][:6]}"
            if entry["only_b"]:
                line += f" | b_sample={entry['only_b'][:6]}"
        print(line)
    return 0


def cmd_columns(args):
    pa, pb = resolve(args.a, args.table), resolve(args.b, args.table)
    if not pa or not pb:
        sys.exit(f"{args.table} missing from one of the sets")
    ta, tb = Table(pa), Table(pb)
    if ta.size != tb.size:
        sys.exit(f"record sizes differ ({ta.size} vs {tb.size}); columns are not comparable")

    ia, ib = ta.records_by_id(), tb.records_by_id()
    if not ia or not ib or len(ia) != ta.count or len(ib) != tb.count:
        sys.exit(f"{args.table}: first column is not a usable unique key; cannot align records")
    shared = [k for k in ia if k in ib]
    per_column = Counter()
    pairs = []
    for key in shared:
        ra, rb = ta.record(ia[key]), tb.record(ib[key])
        if ra == rb:
            continue
        pairs.append((key, ra, rb))
        for column in range(ta.columns):
            if ra[column * 4:column * 4 + 4] != rb[column * 4:column * 4 + 4]:
                per_column[column] += 1

    print(f"# {args.table}: {ta.columns} columns, {len(shared)} shared records,"
          f" {len(pairs)} differing")
    print(f"columns_never_differing: {sum(1 for c in range(ta.columns) if per_column[c] == 0)}")
    print("# as_string is only meaningful for columns that hold string offsets; on a"
          " numeric column the samples are nonsense (see this tool's docstring)")
    for column, count in per_column.most_common(args.top):
        # A column holding a string-block offset differs on almost every record when the
        # string block was repacked, while the text it points at is unchanged. Resolving
        # it separates repacking from real content change.
        same_text = differ_text = 0
        samples = []
        for key, ra, rb in pairs:
            va, vb = ta.column(ra, column), tb.column(rb, column)
            if va == vb:
                continue
            sa, sb = ta.string_at(va), tb.string_at(vb)
            if sa == sb:
                same_text += 1
            else:
                differ_text += 1
                if len(samples) < args.samples:
                    samples.append((key, sa[:48], sb[:48]))
        print(f"  column {column:3d} (byte {column * 4:4d}): {count} records"
              f" | as_string same={same_text} differ={differ_text}")
        for key, sa, sb in samples:
            print(f"      id {key}: a={sa!r} b={sb!r}")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    manifest = sub.add_parser("manifest", help="fingerprint a DBC set")
    manifest.add_argument("directory")
    manifest.add_argument("--id", required=True, help="dataset id, as in client/datasets.yaml")
    manifest.add_argument("--out")
    manifest.set_defaults(func=cmd_manifest)

    compare = sub.add_parser("compare", help="structural delta between two sets")
    compare.add_argument("a")
    compare.add_argument("b")
    compare.set_defaults(func=cmd_compare)

    columns = sub.add_parser("columns", help="per-column delta for one table")
    columns.add_argument("a")
    columns.add_argument("b")
    columns.add_argument("table")
    columns.add_argument("--top", type=int, default=10)
    columns.add_argument("--samples", type=int, default=3)
    columns.set_defaults(func=cmd_columns)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
