#!/usr/bin/env python3
"""Collect, from the UI corpus, the argument names Lua gives each client event.

Two idioms carry them. Ascension's mixins dispatch `OnEvent` to a method named after the
event, so `function ChallengesUI:CHALLENGE_START_RESPONSE(challengeID, level, response)`
names what the event delivers. The development tools' `EventArgNames["EVENT"] = {...}`
table does the same for a few. Both are recorded verbatim with their source line.

These are the EVENT's arguments as Lua receives them, which the handler built from the
packet -- not the packet's fields. They are L2 material for naming a layout, never a
layout by themselves.

  python3 tools/extract/event_args.py <corpus dir> --corpus <id> --out <file>
"""

import argparse
import os
import re
import sys

METHOD = re.compile(r'function\s+[\w.]+:([A-Z][A-Z0-9_]{3,})\s*\(([^)]*)\)')
TABLE = re.compile(r'EventArgNames\["([A-Z0-9_]+)"\]\s*=\s*\{([^}]*)\}')
ALIAS = re.compile(r'EventArgNames\["([A-Z0-9_]+)"\]\s*=\s*EventArgNames\["([A-Z0-9_]+)"\]')
STRING = re.compile(r'"([^"]*)"')


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("corpus_dir")
    parser.add_argument("--corpus", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    events = {}

    def add(event, names, where):
        names = [n.strip() for n in names if n.strip()]
        entry = events.setdefault(event, [])
        for existing in entry:
            if existing["args"] == names:
                if where not in existing["sources"]:
                    existing["sources"].append(where)
                return
        entry.append({"args": names, "sources": [where]})

    tables = {}
    for directory, _, files in sorted(os.walk(args.corpus_dir)):
        for filename in sorted(files):
            if not filename.endswith(".lua"):
                continue
            path = os.path.join(directory, filename)
            rel = os.path.relpath(path, args.corpus_dir).replace(os.sep, "/")
            with open(path, encoding="utf-8-sig", errors="replace") as handle:
                text = handle.read()
            for match in METHOD.finditer(text):
                line = text.count("\n", 0, match.start()) + 1
                params = [p for p in match.group(2).split(",")]
                if params and params[0].strip() == "...":
                    params = ["..."]
                add(match.group(1), params, f"{rel}:{line}")
            for match in TABLE.finditer(text):
                line = text.count("\n", 0, match.start()) + 1
                tables[match.group(1)] = (STRING.findall(match.group(2)), f"{rel}:{line}")
            for match in ALIAS.finditer(text):
                line = text.count("\n", 0, match.start()) + 1
                if match.group(2) in tables:
                    tables[match.group(1)] = (tables[match.group(2)][0], f"{rel}:{line}")
    for event, (names, where) in tables.items():
        add(event, names, where)

    with open(args.out, "w", encoding="utf-8") as out:
        print("# Generated by tools/extract/event_args.py -- do not hand-edit.", file=out)
        print(f"corpus: {args.corpus}", file=out)
        print("evidence: L2", file=out)
        print("# Arguments of the Lua EVENT, as the UI's method named after it (or the", file=out)
        print("# EventArgNames table) declares them. Not packet fields.", file=out)
        print(f"events: {len(events)}", file=out)
        print("definitions:", file=out)
        for event in sorted(events):
            print(f"  {event}:", file=out)
            for entry in events[event]:
                print(f"    - args: [{', '.join(entry['args'])}]", file=out)
                print("      sources:", file=out)
                for where in entry["sources"]:
                    print(f"        - \"{where}\"", file=out)
    print(f"{len(events)} events with argument names -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
