#!/usr/bin/env python3
"""Extract the client's UI source (Lua, XML, TOC) from an MPQ set, and index it.

The client documents itself: its interface code is readable source, and enums, constants
and cost formulas are in it verbatim. This pulls that corpus out so it can be searched.

The corpus is *referenced, not vendored* (ADR 0005): files land outside the repository,
under `build/corpus/<id>/`, and only the manifest — path, size, hash, and which archive
the file came from — is committed.

Archives are applied in the order given on the command line, later overriding earlier.
The tool does not guess the client's own load order: the operator states it, and the
manifest records which archive won for each path.

  python3 tools/extract/extract_ui.py --id <corpus-id> --out build/corpus/<id> \
      --manifest client/corpus/<id>.manifest.yaml <archive.MPQ> [<archive.MPQ> ...]
"""

import argparse
import hashlib
import os
import subprocess
import sys

KEEP = (".lua", ".xml", ".toc")


def list_archive(archive):
    result = subprocess.run(["smpq", "--list", archive],
                            capture_output=True, text=True, check=True)
    names = []
    for line in result.stdout.splitlines():
        parts = line.split(None, 3)
        if len(parts) == 4:
            names.append(parts[3])
    return names


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("archives", nargs="+")
    parser.add_argument("--id", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--prefix", default="Interface/",
                        help="only extract paths starting with this (default: Interface/)")
    args = parser.parse_args()

    if not any(os.access(os.path.join(p, "smpq"), os.X_OK)
               for p in os.environ.get("PATH", "").split(os.pathsep)):
        sys.exit("smpq not found on PATH")

    prefix = args.prefix.lower()
    # Later archives override earlier ones, as the operator ordered them.
    winner = {}
    for archive in args.archives:
        for name in list_archive(archive):
            normalised = name.replace("\\", "/")
            if not normalised.lower().startswith(prefix):
                continue
            if not normalised.lower().endswith(KEEP):
                continue
            winner[normalised] = (archive, name)

    os.makedirs(args.out, exist_ok=True)
    by_archive = {}
    for path, (archive, name) in winner.items():
        by_archive.setdefault(archive, []).append((path, name))

    extracted = 0
    for archive, entries in by_archive.items():
        # smpq extracts using the archive's own paths; run it in the output directory.
        names = [name for _, name in entries]
        for chunk in (names[i:i + 400] for i in range(0, len(names), 400)):
            subprocess.run(["smpq", "--extract", os.path.abspath(archive), *chunk],
                           cwd=args.out, check=True,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        extracted += len(entries)

    os.makedirs(os.path.dirname(args.manifest) or ".", exist_ok=True)
    missing = 0
    with open(args.manifest, "w", encoding="utf-8") as out:
        print("# Generated by tools/extract/extract_ui.py -- do not hand-edit.", file=out)
        print(f"corpus: {args.id}", file=out)
        print(f"prefix: {args.prefix}", file=out)
        print("archives_in_order:", file=out)
        for archive in args.archives:
            print(f"  - {os.path.abspath(archive)}", file=out)
        print(f"extracted_to: {os.path.abspath(args.out)}", file=out)
        print("files:", file=out)
        for path in sorted(winner):
            archive, _ = winner[path]
            local = os.path.join(args.out, path)
            if not os.path.isfile(local):
                missing += 1
                continue
            digest = hashlib.sha256()
            with open(local, "rb") as handle:
                for block in iter(lambda: handle.read(1 << 20), b""):
                    digest.update(block)
            print(f"  - path: {path}", file=out)
            print(f"    sha256: {digest.hexdigest()}", file=out)
            print(f"    bytes: {os.path.getsize(local)}", file=out)
            print(f"    from: {os.path.basename(archive)}", file=out)

    print(f"{extracted} selected, {len(winner) - missing} extracted, {missing} missing")
    print(f"manifest: {args.manifest}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
