#!/usr/bin/env python3
"""Recover the client's Lua API bindings: function name -> implementation address.

The bindings are built on the stack as consecutive `{const char* name, void* fn}` pairs:

    c7 84 24 80 01 00 00  14 7b b3 10    mov [esp+0x180], 0x10b37b14  ; "GetTalentRankByID"
    c7 84 24 84 01 00 00  10 b4 17 10    mov [esp+0x184], 0x1017b410  ; the implementation

Scanning `.text` for a string-valued write immediately followed by a code-valued write
four bytes further up the frame recovers the whole table. Pairing is done within a short
window of bytes, because the same frame offsets are reused by unrelated functions.

This is the bridge from what the UI calls to what the binary does: an addon calls
`C_CharacterAdvancement.GetTalentRankByID`, and this says which function answers.

  python3 tools/extract/lua_bindings.py <Extensions.dll> --build <id> --out <file>
"""

import argparse
import hashlib
import re
import struct
import sys
import os
import importlib.util

IDENTIFIER = re.compile(rb"[A-Za-z_][A-Za-z0-9_]*")
WINDOW = 40  # bytes; the paired write follows almost immediately


def load_image(path):
    spec = importlib.util.spec_from_file_location(
        "opcode_names", os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                     "opcode_names.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.Image(path)


def stack_writes(image, section):
    """Every `mov [esp+disp], imm32`, as (file offset, disp, imm32), in address order."""
    data = image.data
    _, _, _, raw, rsize = section
    offset, end = raw, raw + rsize - 12
    while offset < end:
        if data[offset] == 0xC7 and data[offset + 1] == 0x84 and data[offset + 2] == 0x24:
            yield offset, struct.unpack_from("<I", data, offset + 3)[0], \
                struct.unpack_from("<I", data, offset + 7)[0]
            offset += 11
        elif data[offset] == 0xC7 and data[offset + 1] == 0x44 and data[offset + 2] == 0x24:
            yield offset, data[offset + 3], struct.unpack_from("<I", data, offset + 4)[0]
            offset += 8
        else:
            offset += 1


def identifier_at(image, va):
    start = image.offset(va)
    if start is None:
        return None
    end = image.data.find(b"\0", start)
    text = image.data[start:end]
    return text.decode() if 2 < len(text) < 48 and IDENTIFIER.fullmatch(text) else None


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dll")
    parser.add_argument("--build", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    image = load_image(args.dll)
    section = next(s for s in image.sections if s[0] == ".text")
    low, high = image.base + section[1], image.base + section[1] + section[2]

    writes = list(stack_writes(image, section))
    bindings, ambiguous = {}, set()
    for index, (offset, disp, value) in enumerate(writes):
        name = identifier_at(image, value)
        if not name:
            continue
        for following in writes[index + 1:index + 4]:
            next_offset, next_disp, next_value = following
            if next_offset - offset > WINDOW:
                break
            if next_disp == disp + 4 and low <= next_value < high:
                rva = next_value - image.base
                if name in bindings and bindings[name] != rva:
                    ambiguous.add(name)
                bindings.setdefault(name, rva)
                break

    digest = hashlib.sha256(image.data).hexdigest()
    with open(args.out, "w", encoding="utf-8") as out:
        print("# Generated by tools/extract/lua_bindings.py -- do not hand-edit.", file=out)
        print(f"build: {args.build}", file=out)
        print(f"sha256: {digest}", file=out)
        print(f"image_base: {image.base:#x}", file=out)
        print(f"count: {len(bindings)}", file=out)
        if ambiguous:
            print(f"# {len(ambiguous)} name(s) paired with more than one address; the first"
                  " is kept and they are listed under `ambiguous`.", file=out)
            print("ambiguous:", file=out)
            for name in sorted(ambiguous):
                print(f"  - {name}", file=out)
        print("bindings:", file=out)
        for name in sorted(bindings):
            print(f"  {name}: {bindings[name]:#010x}", file=out)

    print(f"{len(bindings)} bindings ({len(ambiguous)} ambiguous) -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
