#!/usr/bin/env python3
"""Lift `Enum.X = { ... }` tables out of the client's Lua into graded fiche fragments.

Enums are `L2` facts: read directly from client source, authoritative for the names and
values they carry, and true of the corpus they were read from (ADR 0004/0005). Each
output file records the corpus, the source path and the line, so a reader can go back to
it without holding the corpus.

Only simple `name = <integer>` and `name = "<string>"` members are taken. Anything else
in the table (expressions, nested tables, references) is counted and reported as skipped
rather than guessed at.

  python3 tools/extract/lua_enums.py <corpus-dir> --corpus <id> --out protocol/enums \\
      [--only Enum.ResetCreditType --only Enum.CALearnResult]
"""

import argparse
import os
import re
import sys

OPEN_RE = re.compile(r"^(Enum\.[A-Za-z0-9_]+)\s*=\s*\{\s*$")
MEMBER_RE = re.compile(r'^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(-?\d+|"[^"]*")\s*,?\s*$')
CLOSE_RE = re.compile(r"^\s*\}\s*,?\s*$")


def scan(path):
    """Yield (name, line_number, members, skipped) for each top-level Enum table."""
    with open(path, encoding="utf-8", errors="replace") as handle:
        lines = handle.readlines()
    index = 0
    while index < len(lines):
        opened = OPEN_RE.match(lines[index].rstrip("\n"))
        if not opened:
            index += 1
            continue
        start = index + 1
        members, skipped = [], 0
        index += 1
        while index < len(lines) and not CLOSE_RE.match(lines[index]):
            raw = lines[index].split("--", 1)[0].rstrip("\n")
            if raw.strip():
                member = MEMBER_RE.match(raw)
                if member:
                    value = member.group(2)
                    members.append((member.group(1),
                                    value if value.startswith('"') else int(value)))
                else:
                    skipped += 1
            index += 1
        index += 1
        yield opened.group(1), start, members, skipped


def slug(name):
    return name.replace("Enum.", "").replace(".", "-").lower()


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("corpus_dir")
    parser.add_argument("--corpus", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--only", action="append", default=[])
    args = parser.parse_args()

    wanted = set(args.only)
    found = {}
    for root, _, files in os.walk(args.corpus_dir):
        for name in files:
            if not name.lower().endswith(".lua"):
                continue
            path = os.path.join(root, name)
            relative = os.path.relpath(path, args.corpus_dir)
            for enum, line, members, skipped in scan(path):
                if wanted and enum not in wanted:
                    continue
                if not members:
                    continue
                found.setdefault(enum, []).append((relative, line, members, skipped))

    os.makedirs(args.out, exist_ok=True)
    written = 0
    for enum, occurrences in sorted(found.items()):
        target = os.path.join(args.out, f"{slug(enum)}.yaml")
        with open(target, "w", encoding="utf-8") as out:
            print("# Generated by tools/extract/lua_enums.py -- do not hand-edit.", file=out)
            print(f"enum: {enum}", file=out)
            print("evidence: L2", file=out)
            print(f"corpus: {args.corpus}", file=out)
            if len(occurrences) > 1:
                print(f"# Defined {len(occurrences)} times in this corpus; later definitions"
                      f" override earlier ones at load time. All are recorded.", file=out)
            print("definitions:", file=out)
            for relative, line, members, skipped in occurrences:
                print(f"  - source: {relative.replace(os.sep, '/')}", file=out)
                print(f"    line: {line}", file=out)
                if skipped:
                    print(f"    skipped_members: {skipped}"
                          f"   # not a plain name = number/string", file=out)
                print("    members:", file=out)
                for member, value in members:
                    print(f"      {member}: {value}", file=out)
        written += 1

    print(f"{written} enum(s) -> {args.out}")
    multiple = [name for name, occurrences in found.items() if len(occurrences) > 1]
    if multiple:
        print(f"defined more than once: {', '.join(sorted(multiple))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
