#!/usr/bin/env python3
"""Mine the Lua table keys a decompiled builder sets, and the record offset each one reads.

The client turns a record into a Lua table by pushing a key name and then the member it
comes from. In a decompilation that shows up as a string literal (inline, or assigned to a
local right before the push) followed within a few lines by a read at `record + 0xNN`. This
walks a directory of `DumpC.java` output and emits, per function, the keys in source order
with the first record offset seen after each.

The pairing is a heuristic and the output says so: it is a naming aid, to be checked against
the handler's own stores before a fiche claims a field name. What it does establish at `L3`
is that THIS build's binary contains these key names in this function -- which is what turns
a third party's key list into something we re-derived.

    tools/extract/lua_keys.py <dir of .c> --build <id> --out <yaml>
"""
import argparse
import glob
import os
import re

# a key appears either as an inline literal or, when the decompiler hoisted it, as a
# label on the string's address: s_<Key>_10bXXXXX
KEY = re.compile(r'"([A-Za-z][A-Za-z0-9_]{2,40})"|\bs_([A-Za-z][A-Za-z0-9_]{2,40})_10[0-9a-f]{6}\b')
OFFSET = re.compile(r"\+ (0x[0-9a-f]+)\)")
# a literal that is a format string, a path or an event name is not a table key
SKIP = re.compile(r"^(?:[A-Z][A-Z0-9_]{3,}|DBFilesClient|Interface)$")


def mine(path, window):
    keys = []
    lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
    pending = None
    for index, line in enumerate(lines):
        match = KEY.search(line)
        if match:
            name = match.group(1) or match.group(2)
            if not SKIP.match(name):
                pending = (name, index)
        if pending:
            name, at = pending
            if index - at > window:
                keys.append({"key": name, "offset": None})
                pending = None
                continue
            found = [o for o in OFFSET.findall(line) if int(o, 16) >= 0x10]
            if found:
                keys.append({"key": name, "offset": found[0]})
                pending = None
    if pending:
        keys.append({"key": pending[0], "offset": None})
    return keys


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("directory")
    parser.add_argument("--build", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--min-keys", type=int, default=3)
    parser.add_argument("--window", type=int, default=12)
    args = parser.parse_args()

    out = {}
    for path in sorted(glob.glob(os.path.join(args.directory, "*.c"))):
        name = os.path.basename(path)[:-2]
        keys = mine(path, args.window)
        if len(keys) >= args.min_keys:
            out[name] = keys

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("# Generated by tools/extract/lua_keys.py -- do not hand-edit.\n")
        handle.write("# Lua table keys a builder sets, with the first record offset read after each.\n")
        handle.write("# The key names are L3: they are string literals in this build. The key -> offset\n")
        handle.write("# pairing is a heuristic; check it against the handler's stores before using it.\n")
        handle.write(f"build: {args.build}\n")
        handle.write(f"functions: {len(out)}\n")
        handle.write("builders:\n")
        for name in sorted(out):
            handle.write(f"  {name}:\n")
            for entry in out[name]:
                offset = entry["offset"] or "null"
                handle.write(f"    - {{key: {entry['key']}, offset: {offset}}}\n")
    print(f"lua_keys: {len(out)} builders -> {args.out}")


if __name__ == "__main__":
    main()
