#!/usr/bin/env python3
"""Recover which opcodes the client actually handles, and the address of each handler.

Handlers are registered with a plain two-argument call, emitted as:

    68 <handler VA>      push  <handler>
    68 <opcode>          push  <opcode>
    e8 <rel32>           call  <register>

So scanning `.text` for that shape gives the opcode -> handler map directly. A registered
opcode is one the client has code for; an opcode with no registration either travels the
other way (client to server) or is not handled at all -- which is worth knowing before a
server spends effort sending it.

Cross-checks against the name table from `opcode_names.py` when given `--names`.

  python3 tools/extract/opcode_handlers.py <Extensions.dll> --build <id> --out <file> \\
      [--names client/symbols/<build>/opcodes.yaml]
"""

import argparse
import hashlib
import struct
import sys
import importlib.util
import os

PUSH_IMM32 = 0x68
CALL_REL32 = 0xE8
PATTERN_LENGTH = 15  # push imm32, push imm32, call rel32


def load_image(path):
    spec = importlib.util.spec_from_file_location(
        "opcode_names", os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                     "opcode_names.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.Image(path)


def scan(image, max_opcode):
    data = image.data
    section = next(s for s in image.sections if s[0] == ".text")
    _, rva, vsize, raw, rsize = section
    low, high = image.base + rva, image.base + rva + vsize

    found = {}
    offset = raw
    end = raw + rsize - PATTERN_LENGTH
    while offset < end:
        if (data[offset] == PUSH_IMM32 and data[offset + 5] == PUSH_IMM32
                and data[offset + 10] == CALL_REL32):
            handler = struct.unpack_from("<I", data, offset + 1)[0]
            opcode = struct.unpack_from("<I", data, offset + 6)[0]
            if low <= handler < high and opcode <= max_opcode:
                site = rva + (offset - raw)
                relative = struct.unpack_from("<i", data, offset + 11)[0]
                found.setdefault(opcode, []).append({
                    "handler_rva": handler - image.base,
                    "site_rva": site,
                    "register_rva": site + PATTERN_LENGTH + relative,
                })
        offset += 1
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dll")
    parser.add_argument("--build", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--names", help="opcodes.yaml from opcode_names.py")
    parser.add_argument("--max-opcode", type=lambda v: int(v, 0), default=0x9D4)
    args = parser.parse_args()

    image = load_image(args.dll)
    found = scan(image, args.max_opcode)

    names = {}
    if args.names:
        import yaml
        loaded = yaml.safe_load(open(args.names, encoding="utf-8"))
        names = {(int(k, 16) if isinstance(k, str) else int(k)): v
                 for k, v in (loaded.get("opcodes") or {}).items()}

    # One `register` call site dominates; a rare target is worth a human look.
    registrars = {}
    for entries in found.values():
        for entry in entries:
            registrars[entry["register_rva"]] = registrars.get(entry["register_rva"], 0) + 1

    digest = hashlib.sha256(image.data).hexdigest()
    with open(args.out, "w", encoding="utf-8") as out:
        print("# Generated by tools/extract/opcode_handlers.py -- do not hand-edit.", file=out)
        print(f"build: {args.build}", file=out)
        print(f"sha256: {digest}", file=out)
        print(f"image_base: {image.base:#x}", file=out)
        print(f"handled_opcodes: {len(found)}", file=out)
        print("registrars:   # rva of the register function -> number of call sites", file=out)
        for address, count in sorted(registrars.items(), key=lambda kv: -kv[1]):
            print(f"  {address:#010x}: {count}", file=out)
        print("handlers:", file=out)
        for opcode in sorted(found):
            entries = found[opcode]
            print(f"  {opcode:#06x}:", file=out)
            print(f"    name: {names.get(opcode, 'unknown')}", file=out)
            print("    sites:", file=out)
            for entry in entries:
                print(f"      - handler_rva: {entry['handler_rva']:#010x}", file=out)
                print(f"        site_rva: {entry['site_rva']:#010x}", file=out)
                print(f"        register_rva: {entry['register_rva']:#010x}", file=out)

    named_unhandled = sum(1 for op, n in names.items()
                          if n != "unknown" and n.startswith("SMSG") and op not in found)
    print(f"{len(found)} handled opcodes -> {args.out}")
    if names:
        print(f"  SMSG names with no handler registration: {named_unhandled}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
