#!/usr/bin/env python3
"""Recover Ascension's opcode -> name map from Extensions.dll.

The DLL has a function that turns an opcode into its name. It is a plain bounds-checked
switch:

    mov eax, [esp+4]                  ; the opcode
    cmp eax, 0x9d4
    ja  default
    jmp dword ptr [eax*4 + <table>]   ; jump table, one entry per opcode
    ...
    mov eax, <string VA>              ; each case is this, then a ret
    ret

So the jump table IS the map: entry N is the case for opcode N, and the case loads the
address of that opcode's name. This walks it and resolves every name.

The name strings also sit in a packed blob elsewhere in .rdata, in their own order. That
order is NOT the opcode order -- reading it as such is wrong, and the switch is what
settles the numbering.

  python3 tools/extract/opcode_names.py <Extensions.dll> --build <id> --out <file>
"""

import argparse
import hashlib
import struct
import sys

# `mov eax, imm32` / `ret`, the shape of every case in the switch.
MOV_EAX_IMM32 = 0xB8
RET = 0xC3
# mov eax,[esp+4] / cmp eax,imm32 / ja rel32 / jmp [eax*4+imm32]
PROLOGUE = bytes.fromhex("8b442404") + b"\x3d"


class Image:
    def __init__(self, path):
        self.data = open(path, "rb").read()
        pe = struct.unpack_from("<I", self.data, 0x3C)[0]
        count = struct.unpack_from("<H", self.data, pe + 6)[0]
        optional = struct.unpack_from("<H", self.data, pe + 20)[0]
        magic = struct.unpack_from("<H", self.data, pe + 24)[0]
        self.base = (struct.unpack_from("<I", self.data, pe + 24 + 28)[0] if magic == 0x10B
                     else struct.unpack_from("<Q", self.data, pe + 24 + 24)[0])
        table = pe + 24 + optional
        self.sections = []
        for index in range(count):
            entry = table + index * 40
            name = self.data[entry:entry + 8].rstrip(b"\0").decode("ascii", "replace")
            vsize, rva, rsize, raw = struct.unpack_from("<IIII", self.data, entry + 8)
            self.sections.append((name, rva, vsize, raw, rsize))

    def offset(self, va):
        """File offset for a virtual address, or None when it is not backed by the file."""
        rva = va - self.base
        for _, section_rva, vsize, raw, rsize in self.sections:
            if section_rva <= rva < section_rva + vsize and rva - section_rva < rsize:
                return raw + (rva - section_rva)
        return None

    def string(self, va):
        start = self.offset(va)
        if start is None:
            return None
        end = self.data.find(b"\0", start)
        return self.data[start:end].decode("utf-8", "replace")


def find_switch(image):
    """Locate the opcode-name switch: its bound and its jump table address."""
    data = image.data
    position = 0
    while True:
        position = data.find(PROLOGUE, position)
        if position < 0:
            return None, None
        bound = struct.unpack_from("<I", data, position + 5)[0]
        after = position + 9
        # 0f 87 rel32  ja default
        if data[after:after + 2] == b"\x0f\x87":
            after += 6
        # ff 24 85 imm32  jmp [eax*4 + imm32]
        if data[after:after + 3] == b"\xff\x24\x85" and 0x100 < bound < 0x10000:
            return bound, struct.unpack_from("<I", data, after + 3)[0]
        position += 1


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dll")
    parser.add_argument("--build", required=True, help="build id from client/builds.yaml")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    image = Image(args.dll)
    bound, jump_table = find_switch(image)
    if bound is None:
        sys.exit("opcode-name switch not found in this image")
    table_offset = image.offset(jump_table)
    if table_offset is None:
        sys.exit(f"jump table {jump_table:#x} is not backed by the file")

    names, unresolved = {}, 0
    for opcode in range(bound + 1):
        target = struct.unpack_from("<I", image.data, table_offset + opcode * 4)[0]
        case = image.offset(target)
        if case is None or image.data[case] != MOV_EAX_IMM32 or image.data[case + 5] != RET:
            unresolved += 1
            continue
        name = image.string(struct.unpack_from("<I", image.data, case + 1)[0])
        if name is None:
            unresolved += 1
            continue
        names[opcode] = name

    unnamed = sorted(op for op, name in names.items() if name == "unknown")
    digest = hashlib.sha256(image.data).hexdigest()
    with open(args.out, "w", encoding="utf-8") as out:
        print("# Generated by tools/extract/opcode_names.py -- do not hand-edit.", file=out)
        print(f"build: {args.build}", file=out)
        print(f"sha256: {digest}", file=out)
        print(f"image_base: {image.base:#x}", file=out)
        print(f"switch_bound: {bound:#x}   # cmp eax, this; ja default", file=out)
        print(f"jump_table_va: {jump_table:#x}", file=out)
        print(f"opcode_count: {len(names)}", file=out)
        print(f"named: {len(names) - len(unnamed)}", file=out)
        print(f"unnamed: {len(unnamed)}   # the client's own table answers 'unknown'", file=out)
        print("opcodes:", file=out)
        for opcode in sorted(names):
            print(f"  {opcode:#06x}: {names[opcode]}", file=out)

    print(f"{len(names)} opcodes ({len(names) - len(unnamed)} named, {len(unnamed)} 'unknown',"
          f" {unresolved} unresolved) -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
