#!/usr/bin/env python3
"""Which opcodes the CoA server actually sends or handles -- the third leg of "usage".

A client handler says the client has code for a packet; a UI file naming the event says
the interface reacts to it. Neither says whether OUR server ever emits it. This reads the
server module's sources for opcode literals and records, per opcode, the files that use it,
so a fiche can say `used_by_server:`. Those are the opcodes where a wrong layout is shipped
code rather than missing knowledge, which is what makes them the priority.

  python3 tools/extract/server_usage.py <azerothcore checkout> --out <file>
"""

import argparse
import os
import re
import sys

OPCODE = re.compile(r"\b0x0?([0-9A-Fa-f]{3,4})\b")
NAMED = re.compile(r"constexpr\s+uint16\s+(?P<name>[A-Z0-9_]+)\s*=\s*0x(?P<hex>[0-9A-Fa-f]+)")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("core")
    parser.add_argument("--module", action="append", help="repeatable; default: mod-ascension-compat and mod-coa-challenges")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    modules = args.module or ["modules/mod-ascension-compat", "modules/mod-coa-challenges"]
    for module in modules:
        if not os.path.isdir(os.path.join(args.core, module)):
            sys.exit(f"not found: {os.path.join(args.core, module)}")

    usage, names = {}, {}
    for dirpath, _, files in (entry for module in modules for entry in os.walk(os.path.join(args.core, module))):
        for filename in files:
            if not filename.endswith((".cpp", ".h")):
                continue
            path = os.path.join(dirpath, filename)
            relative = os.path.relpath(path, args.core)
            with open(path, encoding="utf-8", errors="replace") as handle:
                text = handle.read()
            # Named constants are the reliable signal; bare literals in the 0x0500-0x09ff
            # range are taken too, since the module writes WorldPacket(0x...) directly.
            for match in NAMED.finditer(text):
                value = int(match.group("hex"), 16)
                names.setdefault(value, set()).add(match.group("name"))
                usage.setdefault(value, set()).add(relative)
            for match in OPCODE.finditer(text):
                value = int(match.group(1), 16)
                if 0x0500 <= value <= 0x09FF:
                    usage.setdefault(value, set()).add(relative)

    with open(args.out, "w", encoding="utf-8") as out:
        print("# Generated by tools/extract/server_usage.py -- do not hand-edit.", file=out)
        print(f"source: {os.path.abspath(args.core)}  # modules: {modules}", file=out)
        print(f"opcode_count: {len(usage)}", file=out)
        print("# Opcode literals between 0x0500 and 0x09FF found in the module's sources, and", file=out)
        print("# every `constexpr uint16 NAME = 0x...`. A bare literal can be a false positive.", file=out)
        print("opcodes:", file=out)
        for value in sorted(usage):
            print(f"  {value:#06x}:", file=out)
            if value in names:
                print(f"    server_names: [{', '.join(sorted(names[value]))}]", file=out)
            print("    files:", file=out)
            for relative in sorted(usage[value]):
                print(f"      - {relative}", file=out)

    print(f"{len(usage)} opcodes used by the server -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
