#!/usr/bin/env python3
"""Classify every fiche and write protocol/COVERAGE.md and protocol/atlas.json.

Coverage here means: for each opcode, what is known and what is explicitly not. Two
axes per fiche --

  client:  handler | sender | handler+sender | none      (code in this client build?)
  layout:  proven | named | widths | empty | prefix | unknown

-- plus whether the UI names an event for it and whether the CoA server uses it.
`atlas.json` is the same data for programs: one object per fiche, sorted by opcode.

  python3 tools/codegen/coverage.py [--check]     (--check: fail if the files would change)
"""

import argparse
import json
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SENDER = re.compile(r"^# client sender: (\S+)", re.M)


def classify(fiche, text):
    client = fiche.get("client") or {}
    handler = (client.get("handler") or {}).get("rva")
    sender = None
    m = SENDER.search(text)
    if m:
        sender = m.group(1).rstrip(",")
    m = re.search(r"read out of the client's sender at (0x[0-9a-f]+)", text)
    if m and not sender:
        sender = m.group(1)
    if handler and sender:
        code = "handler+sender"
    elif handler:
        code = "handler"
    elif sender:
        code = "sender"
    else:
        code = "none"

    layout = fiche.get("layout") or []
    if fiche.get("status") == "proven":
        shape = "proven"
    elif layout and all(str(f.get("name", "")).startswith("field_") for f in layout if "repeat" not in f):
        shape = "widths"
    elif layout:
        shape = "named"
    elif re.search(r"layout: \[\]\s*#\s*empty", text):
        shape = "empty"
    elif "PREFIX of the payload" in text:
        shape = "prefix"
    else:
        shape = "unknown"
    return code, shape, handler, sender


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    with open(os.path.join(ROOT, "protocol", "known-baseline.yaml"), encoding="utf-8") as handle:
        baseline = yaml.safe_load(handle)
    server_names = {(int(k, 16) if isinstance(k, str) else int(k)): v
                    for k, v in (baseline.get("fork_opcodes") or {}).items()}

    directory = os.path.join(ROOT, "protocol", "opcodes")
    rows = []
    for filename in sorted(os.listdir(directory)):
        if not filename.endswith(".yaml"):
            continue
        path = os.path.join(directory, filename)
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        fiche = yaml.safe_load(text)
        code, shape, handler, sender = classify(fiche, text)
        rows.append({
            "id": fiche["id"], "hex": f"0x{fiche['id']:04X}", "name": fiche["name"],
            "direction": fiche["direction"], "status": fiche["status"], "evidence": fiche["evidence"],
            "server_name": server_names.get(fiche["id"]),
            "file": f"protocol/opcodes/{filename}",
            "summary": " ".join(str(fiche.get("summary", "")).split()),
            "client_code": code, "layout_state": shape,
            "handler_rva": handler, "sender": sender,
            "layout": [{k: v for k, v in f.items()} for f in (fiche.get("layout") or [])],
            "events": [e["event"] for e in (fiche.get("client_events") or [])],
            "fires": [{"event": f.get("event"), "format": f.get("format")} for f in (fiche.get("client_fire") or [])],
            "client_strings": fiche.get("client_strings") or [],
            "used_by_ui": fiche.get("used_by") or [],
            "used_by_server": (fiche.get("used_by_server") or {}).get("files") or [],
            "replay": (fiche.get("replay") or {}).get("script") if isinstance(fiche.get("replay"), dict) else None,
            "client_builds": fiche.get("client_builds") or [],
        })

    def count(key):
        out = {}
        for row in rows:
            out.setdefault(row["direction"], {}).setdefault(row[key], 0)
            out[row["direction"]][row[key]] += 1
        return out

    by_code, by_shape = count("client_code"), count("layout_state")
    directions = ["client_to_server", "server_to_client"]
    lines = ["# Coverage", "",
             "Generated by `tools/codegen/coverage.py` -- do not hand-edit. One row per fiche; the two",
             "columns that matter are **client code** (is there a handler or a sender in this build?) and",
             "**layout** (proven > named > widths > empty > prefix > unknown). `atlas.json` next to this",
             "file holds the same data for programs.", "",
             f"{len(rows)} fiches.", "",
             "## By client code", "", "| direction | " + " | ".join(["handler+sender", "handler", "sender", "none"]) + " |",
             "| --- | --- | --- | --- | --- |"]
    for d in directions:
        lines.append(f"| {d} | " + " | ".join(str(by_code.get(d, {}).get(k, 0)) for k in ["handler+sender", "handler", "sender", "none"]) + " |")
    shapes = ["proven", "named", "widths", "empty", "prefix", "unknown"]
    lines += ["", "## By layout", "", "| direction | " + " | ".join(shapes) + " |", "| --- |" + " --- |" * len(shapes)]
    for d in directions:
        lines.append(f"| {d} | " + " | ".join(str(by_shape.get(d, {}).get(k, 0)) for k in shapes) + " |")
    lines += ["", "`none` + `unknown` is a name with nothing behind it in this build: no handler, no sender,",
              "no trace of the opcode (see `client/client-senders.md`). `handler` + `unknown` is a handler",
              "whose reads neither extractor could follow; the fiche names its RVA for a reader.", "",
              "## Every opcode", "", "| opcode | name | dir | status | code | layout | events | server |",
              "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    for row in rows:
        lines.append(f"| `{row['hex']}` | [{row['name']}]({row['file'].replace('protocol/', '')}) | "
                     f"{'C>S' if row['direction'] == 'client_to_server' else 'S>C'} | {row['status']} | "
                     f"{row['client_code']} | {row['layout_state']} | {len(row['events'])} | "
                     f"{'yes' if row['used_by_server'] else ''} |")
    md = "\n".join(lines) + "\n"
    js = json.dumps({"generated_by": "tools/codegen/coverage.py", "fiches": rows}, indent=1, sort_keys=True) + "\n"

    targets = {os.path.join(ROOT, "protocol", "COVERAGE.md"): md, os.path.join(ROOT, "protocol", "atlas.json"): js}
    changed = []
    for path, content in targets.items():
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current != content:
            changed.append(os.path.relpath(path, ROOT))
            if not args.check:
                with open(path, "w", encoding="utf-8") as handle:
                    handle.write(content)
    if args.check and changed:
        print("coverage: out of date: " + ", ".join(changed) + " -- run tools/codegen/coverage.py")
        return 1
    print(f"coverage: {len(rows)} fiches -> protocol/COVERAGE.md, protocol/atlas.json" + (" (unchanged)" if not changed else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
