#!/usr/bin/env python3
"""Emit consumer files from the fiches: a C++ header, a Go file and a Wireshark dissector.

Everything comes from protocol/atlas.json (run coverage.py first), so a consumer and the
documentation cannot disagree: the header carries each opcode's layout state and evidence
level in a comment, and the dissector only decodes layouts whose widths the atlas holds.

  generated/ascension_opcodes.h     constexpr uint16 per opcode, namespace Ascension::Opcode
  generated/ascension_opcodes.go    package ascension: consts and a Name map
  generated/ascension.lua           Wireshark: plaintext world framing on port 8085, one
                                    subtree per opcode with widths (repeat blocks opaque)

  python3 tools/codegen/emit.py [--check]
"""

import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LUA_TYPES = {"u8": ("uint8", 1), "u16": ("uint16", 2), "u32": ("uint32", 4), "u64": ("uint64", 8),
             "i8": ("int8", 1), "i16": ("int16", 2), "i32": ("int32", 4), "f32": ("float", 4),
             "float": ("float", 4), "bool": ("uint8", 1), "cstring": ("stringz", None),
             "lpstring": ("lpstring", None), "packed_guid": ("packed_guid", None)}


def camel(name):
    return "".join(part.capitalize() for part in name.lower().split("_"))


def header(rows):
    out = ["// Generated by tools/codegen/emit.py from the CoA Protocol Atlas -- do not hand-edit.",
           "// One constant per documented Ascension opcode. The comment says what the atlas knows:",
           "// direction, layout state (proven > named > widths > empty > prefix > unknown) and the",
           "// fiche's evidence level. Anything below L3 must not be relied on in server code.",
           "#pragma once", "", "#include <cstdint>", "", "namespace Ascension::Opcode", "{"]
    for row in rows:
        direction = "C>S" if row["direction"] == "client_to_server" else "S>C"
        alias = f"; mod-ascension-compat calls it {row['server_name']}" if row.get("server_name") else ""
        out.append(f"    constexpr uint16_t {row['name']} = {row['hex']};  // {direction} {row['layout_state']} {row['evidence']}{alias}")
    out += ["}", ""]
    return "\n".join(out)


def go(rows):
    # One declaration per line and a map filled in init(): nothing gofmt would realign.
    out = ["// Code generated by tools/codegen/emit.py from the CoA Protocol Atlas; DO NOT EDIT.", "",
           "package ascension", "",
           "// Opcode values documented by the atlas; each comment gives direction, layout state and evidence level.", ""]
    for row in rows:
        direction = "C>S" if row["direction"] == "client_to_server" else "S>C"
        out.append(f"// {camel(row['name'])}: {direction} {row['layout_state']} {row['evidence']}")
        out.append(f"const {camel(row['name'])} uint16 = {row['hex']}")
        out.append("")
    out += ["// Name maps every documented opcode to the client's own name for it.", "var Name = map[uint16]string{}", "",
            "func init() {"]
    for row in rows:
        out.append(f"\tName[{camel(row['name'])}] = \"{row['name']}\"")
    out += ["}", ""]
    return "\n".join(out)


def lua_fields(layout):
    fields = []
    for field in layout:
        if "repeat" in field:
            return None                          # a counted record: left opaque in this generation
        kind = LUA_TYPES.get(str(field.get("type")))
        if kind is None:
            m = re.match(r"bytes_(\d+)$", str(field.get("type")))
            if not m:
                return None
            kind = ("bytes", int(m.group(1)))
        fields.append((str(field.get("name")), kind[0], kind[1]))
    return fields


def dissector(rows):
    out = ['-- Generated by tools/codegen/emit.py from the CoA Protocol Atlas -- do not hand-edit.',
           '-- Dissects Ascension custom opcodes in PLAINTEXT world framing on TCP 8085: a 2-byte',
           '-- big-endian size, then a 2-byte (client to server: 4-byte) little-endian opcode, then the',
           '-- payload. Live 3.3.5a traffic encrypts the header with the session key; this dissector',
           '-- is for a lab server running with plaintext headers or for already-decrypted dumps.',
           '-- Layouts come from the fiches: only widths the atlas holds are decoded, repeat blocks',
           '-- and unknown lengths stop the walk and the rest is shown as bytes.',
           'local proto = Proto("ascension", "Ascension custom protocol")',
           'local f_opcode = ProtoField.uint16("ascension.opcode", "Opcode", base.HEX)',
           'local f_name = ProtoField.string("ascension.name", "Name")',
           'local f_field = ProtoField.bytes("ascension.field", "Field")',
           'proto.fields = { f_opcode, f_name, f_field }', '',
           'local names = {}', 'local layouts = {}']
    for row in rows:
        out.append(f'names[{row["hex"]}] = "{row["name"]}"')
        fields = lua_fields(row["layout"]) if row["layout"] else []
        if fields:
            items = ", ".join(f'{{"{n}", "{k}", {w if w is not None else "nil"}}}' for n, k, w in fields)
            out.append(f'layouts[{row["hex"]}] = {{ {items} }}')
    out += ['',
            'local function walk(tree, buf, layout)',
            '  local pos = 0',
            '  for _, field in ipairs(layout) do',
            '    local name, kind, width = field[1], field[2], field[3]',
            '    if kind == "stringz" then',
            '      local zero = pos',
            '      while zero < buf:len() and buf(zero, 1):uint() ~= 0 do zero = zero + 1 end',
            '      tree:add(f_field, buf(pos, zero - pos + 1)):set_text(name .. " (cstring): " .. buf(pos, zero - pos):string())',
            '      pos = zero + 1',
            '    elseif kind == "lpstring" then',
            '      if pos + 4 > buf:len() then return pos end',
            '      local len = buf(pos, 4):le_uint()',
            '      tree:add(f_field, buf(pos, 4 + len)):set_text(name .. " (lpstring[" .. len .. "]): " .. buf(pos + 4, len):string())',
            '      pos = pos + 4 + len',
            '    elseif kind == "packed_guid" then',
            '      return pos',
            '    else',
            '      if width == nil or pos + width > buf:len() then return pos end',
            '      local r = buf(pos, width)',
            '      local text',
            '      if kind == "float" then text = tostring(r:le_float())',
            '      elseif kind == "bytes" then text = tostring(r)',
            '      elseif kind == "uint64" then text = tostring(r:le_uint64())',
            '      else text = tostring(r:le_uint()) end',
            '      tree:add(f_field, r):set_text(name .. " (" .. kind .. "): " .. text)',
            '      pos = pos + width',
            '    end',
            '  end',
            '  return pos',
            'end', '',
            'function proto.dissector(buf, pinfo, tree)',
            '  if buf:len() < 4 then return end',
            '  local to_server = pinfo.dst_port == 8085',
            '  local size = buf(0, 2):uint()',
            '  local opwidth = to_server and 4 or 2',
            '  if buf:len() < 2 + opwidth then return end',
            '  local opcode = buf(2, opwidth):le_uint()',
            '  local name = names[opcode]',
            '  if not name then return end',
            '  pinfo.cols.protocol = "ASCENSION"',
            '  pinfo.cols.info = name',
            '  local sub = tree:add(proto, buf(), "Ascension " .. name)',
            '  sub:add(f_opcode, buf(2, opwidth), opcode)',
            '  sub:add(f_name, name)',
            '  local payload = buf(2 + opwidth)',
            '  local layout = layouts[opcode]',
            '  local consumed = 0',
            '  if layout then consumed = walk(sub, payload, layout) end',
            '  if consumed < payload:len() then',
            '    sub:add(f_field, payload(consumed)):set_text("undecoded: " .. tostring(payload(consumed)))',
            '  end',
            'end', '',
            'DissectorTable.get("tcp.port"):add(8085, proto)', '']
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with open(os.path.join(ROOT, "protocol", "atlas.json"), encoding="utf-8") as handle:
        rows = json.load(handle)["fiches"]
    targets = {"generated/ascension_opcodes.h": header(rows), "generated/ascension_opcodes.go": go(rows),
               "generated/ascension.lua": dissector(rows)}
    changed = []
    for rel, content in targets.items():
        path = os.path.join(ROOT, rel)
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current != content:
            changed.append(rel)
            if not args.check:
                with open(path, "w", encoding="utf-8") as handle:
                    handle.write(content)
    if args.check and changed:
        print("emit: out of date: " + ", ".join(changed) + " -- run tools/codegen/emit.py")
        return 1
    print(f"emit: {len(rows)} opcodes -> " + ", ".join(targets) + (" (unchanged)" if not changed else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
