#!/usr/bin/env python3
"""Generate `protocol/INDEX.md`: what is known about every documented opcode, at a glance.

753 fiches are not browsable as a directory listing. This renders them as one table
ordered by opcode, with the evidence level, whether the client has a handler, how many
fields are recovered, and whether the UI names the event — so the next person can see
where the gaps are instead of opening files at random.

  python3 tools/codegen/index.py
"""

import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def main():
    directory = os.path.join(ROOT, "protocol", "opcodes")
    rows, levels, with_handler, with_layout, with_usage, with_server = [], {}, 0, 0, 0, 0
    for filename in sorted(os.listdir(directory)):
        if not filename.endswith(".yaml"):
            continue
        with open(os.path.join(directory, filename), encoding="utf-8") as handle:
            fiche = yaml.safe_load(handle)
        layout = fiche.get("layout") or []
        def count(entries):
            return sum(count(f.get("fields") or []) if "repeat" in f else 1 for f in entries)
        fields = count(layout)
        handler = "yes" if (fiche.get("client") or {}).get("handler") else ""
        usage = len(fiche.get("used_by") or [])
        server = "yes" if fiche.get("used_by_server") else ""
        level = fiche.get("evidence", "?")
        levels[level] = levels.get(level, 0) + 1
        with_handler += bool(handler)
        with_layout += bool(fields)
        with_usage += bool(usage)
        with_server += bool(server)
        rows.append((fiche["id"], fiche["name"], fiche.get("status", "?"), level,
                     handler, fields, usage, server, filename))

    path = os.path.join(ROOT, "protocol", "INDEX.md")
    with open(path, "w", encoding="utf-8") as out:
        print("<!-- Generated by tools/codegen/index.py -- do not hand-edit. -->", file=out)
        print("# Opcode index\n", file=out)
        print(f"{len(rows)} fiches. **Fields** is how many the layout carries, which is a", file=out)
        print("skeleton from `packet_layout.py` unless someone has worked on the fiche;", file=out)
        print("**UI** is how many interface files name the opcode's event.\n", file=out)
        print("| | count |", file=out)
        print("| --- | --- |", file=out)
        print(f"| fiches | {len(rows)} |", file=out)
        print(f"| with a registered handler | {with_handler} |", file=out)
        print(f"| with a recovered layout | {with_layout} |", file=out)
        print(f"| named by the UI | {with_usage} |", file=out)
        print(f"| sent or handled by the CoA server | {with_server} |", file=out)
        for level in sorted(levels):
            print(f"| evidence {level} | {levels[level]} |", file=out)
        print("\n| Opcode | Name | Status | Evidence | Handler | Fields | UI | Server |", file=out)
        print("| --- | --- | --- | --- | --- | --- | --- | --- |", file=out)
        for opcode, name, status, level, handler, fields, usage, server, filename in rows:
            print(f"| [`{opcode:#06x}`](opcodes/{filename}) | `{name}` | {status} |"
                  f" {level} | {handler} | {fields or ''} | {usage or ''} | {server} |", file=out)

    print(f"{len(rows)} fiches indexed -> protocol/INDEX.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
