#!/usr/bin/env python3
"""Render the atlas as a set of Markdown pages GitHub Pages can serve as-is (Jekyll).

  site/index.md              coverage summary and the opcode table
  site/opcodes/<hex>.md      one page per fiche, from protocol/atlas.json
  site/_config.yml           theme only

No dependency: the pages are Markdown, the fiche's own text, rendered by Pages when the
repository is public. Regenerated by tools/regenerate.sh; CI checks they are current.

  python3 tools/codegen/site.py [--check]
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def page(row):
    lines = [f"# `{row['hex']}` {row['name']}", "",
             f"**{row['direction'].replace('_', ' ')}** · status `{row['status']}` · evidence `{row['evidence']}` · "
             f"layout `{row['layout_state']}` · client code `{row['client_code']}`", "",
             f"Fiche: [`{row['file']}`](../../{row['file']})", ""]
    if row.get("server_name"):
        lines += [f"The CoA server calls it `{row['server_name']}`.", ""]
    lines += [row["summary"], "", "## Layout", ""]
    if row["layout"]:
        lines += ["| field | type | evidence | notes |", "| --- | --- | --- | --- |"]

        def emit(entries, prefix):
            for field in entries:
                if "repeat" in field:
                    lines.append(f"| {prefix}*repeat × {field.get('repeat')}* | | | |")
                    emit(field.get("fields") or [], prefix + "&nbsp;&nbsp;")
                else:
                    lines.append(f"| {prefix}`{field.get('name')}` | `{field.get('type')}` | {field.get('evidence', '')} | {str(field.get('notes', '')).replace('|', '/')} |")
        emit(row["layout"], "")
    else:
        lines.append("*No layout established.*")
    if row["handler_rva"] or row["sender"]:
        lines += ["", "## Client", ""]
        if row["handler_rva"]:
            lines.append(f"- handler RVA `{row['handler_rva']}` in `{', '.join(row['client_builds'])}`")
        if row["sender"]:
            lines.append(f"- sender `{row['sender']}`")
    if row["fires"] or row["events"]:
        lines += ["", "## Events", ""]
        for f in row["fires"]:
            lines.append(f"- fires `{f['event']}`" + (f" with format `{f['format']}`" if f.get("format") else ""))
        for e in row["events"]:
            lines.append(f"- the UI receives `{e}` (`client/event-args.yaml`)")
    if row["used_by_server"]:
        lines += ["", "## Server", ""] + [f"- `{f}`" for f in row["used_by_server"]]
    if row["replay"]:
        lines += ["", "## Replay", "", f"`{row['replay']}`"]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with open(os.path.join(ROOT, "protocol", "atlas.json"), encoding="utf-8") as handle:
        rows = json.load(handle)["fiches"]

    targets = {}
    for row in rows:
        targets[f"site/opcodes/{row['hex']}.md"] = page(row)
    from collections import Counter
    states = Counter(r["layout_state"] for r in rows)
    index = ["# CoA Protocol Atlas", "",
             "The Ascension 3.3.5a custom protocol, rebuilt from the client and graded by evidence.",
             "Every page is one opcode's fiche; the levels are in [`docs/EVIDENCE.md`](../docs/EVIDENCE.md).", "",
             f"{len(rows)} opcodes · " + " · ".join(f"{k} {v}" for k, v in sorted(states.items())), "",
             "| opcode | name | dir | status | layout | code |", "| --- | --- | --- | --- | --- | --- |"]
    for row in rows:
        index.append(f"| [`{row['hex']}`](opcodes/{row['hex']}.md) | {row['name']} | {'C>S' if row['direction'] == 'client_to_server' else 'S>C'} | {row['status']} | {row['layout_state']} | {row['client_code']} |")
    targets["site/index.md"] = "\n".join(index) + "\n"
    targets["site/_config.yml"] = "theme: jekyll-theme-minimal\ntitle: CoA Protocol Atlas\ndescription: the Ascension 3.3.5a custom protocol, graded by evidence\n"

    changed = []
    for rel, content in targets.items():
        path = os.path.join(ROOT, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current != content:
            changed.append(rel)
            if not args.check:
                with open(path, "w", encoding="utf-8") as handle:
                    handle.write(content)
    # pages for fiches that no longer exist
    existing = {os.path.join("site", "opcodes", f) for f in os.listdir(os.path.join(ROOT, "site", "opcodes"))} if os.path.isdir(os.path.join(ROOT, "site", "opcodes")) else set()
    stale = existing - {k for k in targets if k.startswith("site/opcodes/")}
    for rel in stale:
        changed.append(rel)
        if not args.check:
            os.remove(os.path.join(ROOT, rel))
    if args.check and changed:
        print("site: out of date (" + ", ".join(changed[:5]) + (" ..." if len(changed) > 5 else "") + ") -- run tools/codegen/site.py")
        return 1
    print(f"site: {len(rows)} pages -> site/" + (" (unchanged)" if not changed else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
