#!/usr/bin/env python3
"""Generate one stub fiche per custom opcode, from what the binary already told us.

Turns the raw symbol files into the canonical fiche format so the remaining work is
visible and trackable: a name, a direction, the handler's RVA when the client registers
one, and the UI files that mention the opcode's event name. Everything else is left for a
human to establish -- the stubs carry `status: unknown` and no layout, because a name is
not a wire format.

A stub is never overwritten. Once someone has written into a fiche, this tool skips it.

  python3 tools/codegen/stub_fiches.py --build <id> [--corpus <dir>] [--dry-run]
"""

import argparse
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DIRECTIONS = {"SMSG": "server_to_client", "CMSG": "client_to_server"}


def load(path):
    with open(os.path.join(ROOT, path), encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def as_opcode_map(section):
    return {(int(k, 16) if isinstance(k, str) else int(k)): v for k, v in section.items()}


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def corpus_index(directory):
    """Every UI source file's text, keyed by path relative to the corpus root."""
    files = {}
    if not directory or not os.path.isdir(directory):
        return files
    for dirpath, _, names in os.walk(directory):
        for name in names:
            if not name.lower().endswith((".lua", ".xml", ".toc")):
                continue
            path = os.path.join(dirpath, name)
            try:
                with open(path, encoding="utf-8", errors="replace") as handle:
                    files[os.path.relpath(path, directory)] = handle.read()
            except OSError:
                continue
    return files


def mentions(corpus, name):
    """UI files naming this opcode's event, i.e. its name without the direction prefix."""
    stem = re.sub(r"^(SMSG|CMSG|UMSG|MSG)_", "", name)
    if len(stem) < 8:            # too short to match without false positives
        return []
    return sorted(path for path, text in corpus.items() if stem in text)


def write(path, text, dry_run):
    if os.path.exists(path):
        return "exists"
    if dry_run:
        return "would-create"
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return "created"


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--build", required=True)
    parser.add_argument("--corpus", default="build/corpus/ascension-ui-patch-b-stock")
    parser.add_argument("--dataset", default="ascension-live-2026-09-17")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    symbols = f"client/symbols/{args.build}"
    names = as_opcode_map(load(f"{symbols}/opcodes.yaml")["opcodes"])
    handlers = as_opcode_map(load(f"{symbols}/handlers.yaml")["handlers"])
    baseline = as_opcode_map(load("protocol/known-baseline.yaml")["opcodes"])
    corpus = corpus_index(os.path.join(ROOT, args.corpus))

    out = os.path.join(ROOT, "protocol", "opcodes")
    counts = {"created": 0, "exists": 0, "would-create": 0, "skipped": 0}
    # A fiche may already exist under a hand-chosen filename; key existence on the opcode.
    existing = {int(f.split("-", 1)[0], 16) for f in os.listdir(out) if f.endswith(".yaml")}
    for opcode, name in sorted(names.items()):
        if opcode in baseline:
            continue                                    # standard 3.3.5a, whatever the client calls it (ADR 0005)
        if name in ("MSG_NULL", "MAX") or name.startswith("UMSG_"):
            continue                                    # table markers and client-internal messages, not wire opcodes
        handler = handlers.get(opcode)
        if name == "unknown":
            # The client's own table has no name, but if it registers a handler there is
            # code behind the number, and that is worth a fiche. The direction is known
            # from the registration itself: a handler receives, so it is server-to-client.
            if not handler:
                continue
            name, prefix, unnamed = f"SMSG_UNNAMED_{opcode:04X}", "SMSG", True
        else:
            prefix, unnamed = name.split("_", 1)[0], False
        if prefix not in DIRECTIONS:                    # MSG_/UMSG_, no filename form
            counts["skipped"] += 1
            continue

        used_in = mentions(corpus, name)
        renamed = baseline.get(opcode)

        lines = [
            "# Generated by tools/codegen/stub_fiches.py. Nothing here is a wire format:",
            "# a name and a handler address say what the client calls this and that it has",
            "# code for it, not what the packet contains. Fill in `layout` from evidence.",
            f"id: {opcode:#06x}",
            f"name: {name}"
            + ("   # PLACEHOLDER: the client's table answers 'unknown'; a handler exists"
               if unnamed else ""),
            f"direction: {DIRECTIONS[prefix]}",
            "status: unknown",
            "evidence: L3",
            "client_builds:",
            f"  - {args.build}",
        ]
        if used_in:
            lines += ["client_datasets:", f"  - {args.dataset}"]
        lines += ["", "summary: >"]
        if unnamed:
            lines += [
                f"  Unnamed in the client's own opcode table, but the client registers a",
                f"  handler for {opcode:#06x} -- there is code behind it. Direction inferred from",
                "  that registration. Layout and behaviour not established.",
            ]
        else:
            lines += [
                f"  Named {name} by the client's own opcode table. Layout and behaviour not",
                "  established.",
            ]
        lines.append("")
        if renamed:
            lines += [
                "reuses_standard_opcode: true",
                f"# AzerothCore calls {opcode:#06x} {renamed}. Ascension uses the number for",
                "# something else; which of the two a given realm means is worth checking.",
                "",
            ]
        lines += ["layout: []   # unknown", ""]
        if handler:
            site = handler["sites"][0]
            lines += [
                "client:",
                "  handler:",
                f"    rva: \"{site['handler_rva']:#010x}\"",
                f"    registration_site_rva: \"{site['site_rva']:#010x}\"",
                "    evidence: L3",
                "",
            ]
        if used_in:
            lines += ["used_by:   # UI source naming this opcode's event"]
            for path in used_in[:8]:
                lines.append(f"  - {path}")
            if len(used_in) > 8:
                lines.append(f"  # and {len(used_in) - 8} more")
            lines.append("")
        lines += ["provenance:"]
        if unnamed:
            lines += [
                "  - level: L3",
                f"    source: \"{symbols}/opcodes.yaml (opcode-name switch)\"",
                f"    claim: \"the client's table has no name for {opcode:#06x}\"",
            ]
        else:
            lines += [
                "  - level: L3",
                f"    source: \"{symbols}/opcodes.yaml (opcode-name switch)\"",
                f"    claim: \"opcode {opcode:#06x} is named {name}\"",
            ]
        if handler:
            lines += [
                "  - level: L3",
                f"    source: \"{symbols}/handlers.yaml (handler registration scan)\"",
                "    claim: \"the client registers a handler for it\"",
            ]
        if used_in:
            lines += [
                "  - level: L2",
                f"    source: \"corpus {os.path.basename(args.corpus)}\"",
                "    claim: \"the UI names this event\"",
            ]
        lines += ["", "replay: null", ""]

        filename = f"{opcode:#06x}-{prefix.lower()}-{slug(name.split('_', 1)[1])}.yaml"
        if unnamed:
            filename = f"{opcode:#06x}-smsg-unnamed.yaml"
        if opcode in existing:
            counts["exists"] += 1
            continue
        counts[write(os.path.join(out, filename), "\n".join(lines), args.dry_run)] += 1

    for key, value in counts.items():
        print(f"{key}: {value}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
