// For each handler address listed in the input file (one hex VA per line, with the opcode
// after a space), decompile it and print every string literal the C references, plus the
// names of functions it calls that Ghidra could name. Output is one YAML block per opcode.
import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.*;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import java.io.*;
import java.util.*;
import java.util.regex.*;

public class HandlerStrings extends GhidraScript {
    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        BufferedReader in = new BufferedReader(new FileReader(args[0]));
        PrintWriter out = new PrintWriter(new FileWriter(args[1]));
        DecompInterface ifc = new DecompInterface();
        ifc.openProgram(currentProgram);
        Pattern str = Pattern.compile("\"((?:[^\"\\\\]|\\\\.){2,120})\"");
        // Ghidra's label for a string literal (s_..._<address>) is cut at its label length
        // limit, so the literal is read back from memory at the address the label carries.
        Pattern dat = Pattern.compile("s_[A-Za-z0-9_]+_(10[0-9a-f]{6})");
        out.println("# Generated by tools/ghidra/scripts/HandlerStrings.java -- do not hand-edit.");
        out.println("handlers:");
        String line; int n = 0;
        while ((line = in.readLine()) != null) {
            String[] parts = line.trim().split("\\s+");
            if (parts.length < 2) continue;
            Address addr = currentProgram.getImageBase().getNewAddress(Long.parseLong(parts[0], 16));
            Function f = getFunctionContaining(addr);
            if (f == null) {                 // Ghidra defines no function at some registered handlers: create one
                disassemble(addr);
                f = createFunction(addr, "handler_" + parts[1]);
            }
            out.println("  " + parts[1] + ":");
            if (f == null) { out.println("    strings: []"); continue; }
            DecompileResults r = ifc.decompileFunction(f, 45, monitor);
            if (!r.decompileCompleted()) { out.println("    strings: []"); continue; }
            String c = r.getDecompiledFunction().getC();
            LinkedHashSet<String> found = new LinkedHashSet<>();
            Matcher m = str.matcher(c);
            while (m.find()) found.add(m.group(1));
            Matcher d = dat.matcher(c);
            while (d.find()) {
                Address a = toAddr(Long.parseLong(d.group(1), 16));
                StringBuilder sb = new StringBuilder();
                boolean printable = true;
                for (int i = 0; i < 256; i++) {
                    byte b = getByte(a.add(i));
                    if (b == 0) break;
                    if (b < 0x20 || b > 0x7e) { printable = false; break; }
                    sb.append((char) b);
                }
                // a label whose bytes are not a plain C string keeps its (possibly cut) label text
                found.add(printable && sb.length() > 1 ? sb.toString() : d.group(0).substring(2, d.group(0).length() - 9));
            }
            out.println("    strings:");
            for (String s : found) out.println("      - \"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"");
            if (++n % 50 == 0) println("decompiled " + n);
        }
        out.close();
        println("done: " + n);
    }
}
